actors:
  nrt_nn:
    image_url: /images/actors/nrt_nn.jpg
    name: nrt_nn
    url: https://twitter.com/nrt_nn
  wktk0:
    image_url: /images/actors/wktk0.jpg
    name: wktk0
    url: https://twitter.com/wktk0
author: nrt_nn, wktk0
description: 寿司とかわいいを愛してやまない人らによるあの日あの時あの頃の孤独を思い起こす旅路
description_long: もう寝ろ
email: info@example.com
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: sushi
itunes_podcast_url:
keywords: comma,separated,keywords
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: オールウェイズ惰眠を貪る
url: https://gabdro.github.io
