actors:
  alice:
    image_url: /images/actors/nrt_nn_400x400.png
    name: nrt_nn
    url: http://sns.example.com/alice
  bob:
    image_url: /images/actors/wktk0_400x400.png
    name: so a.k.a wktk0
    url: http://sns.example.com/bob
author: @NRT_Nn @wktk0
description: オールウェイズ惰眠を貪る
description_long: もう寝ろ
email: info@example.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: examplehashtag
itunes_podcast_url:
keywords: comma,separated,keywords
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: Example title
url: gabdro.github.io/
